-- Inserções de livros na tabela tb_book
-- Cada linha adiciona um livro com título, autor, gênero, URL da imagem, ano de publicação e descrição
INSERT INTO tb_book (title, author, genre, img_url, book_year, assessment, descri) VALUES ('O Senhor dos Anéis: A Sociedade do Anel', 'J.R.R. Tolkien', 'Fantasia', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/book1.png', 1954, 5, 'Um épico de fantasia que segue a jornada de Frodo Bolseiro para destruir o Anel do Poder.');
INSERT INTO tb_book (title, author, genre, img_url, book_year, assessment, descri) VALUES ('1984', 'George Orwell', 'Distopia', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/book2.png', 1949, 5, 'Uma visão sombria e assustadora de um regime totalitário que controla todos os aspectos da vida.');
INSERT INTO tb_book (title, author, genre, img_url, book_year, assessment, descri) VALUES ('Dom Quixote', 'Miguel de Cervantes', 'Clássico', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/book3.png', 1605, 5, 'A história de um homem que, em sua busca por aventuras, confunde moinhos de vento com gigantes.');
INSERT INTO tb_book (title, author, genre, img_url, book_year, assessment, descri) VALUES ('Orgulho e Preconceito', 'Jane Austen', 'Romance', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/book4.png', 1813, 5, 'Uma história de amor, classe social e preconceitos em um romance inglês do século XIX.');
INSERT INTO tb_book (title, author, genre, img_url, book_year, assessment, descri) VALUES ('Moby Dick', 'Herman Melville', 'Aventura', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/book5.png', 1851, 5, 'A busca obsessiva do Capitão Ahab pela grande baleia branca, Moby Dick.');
INSERT INTO tb_book (title, author, genre, img_url, book_year, assessment, descri) VALUES ('Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'Fantasia', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/book6.png', 1997, 5, 'A introdução ao mundo mágico de Harry Potter e sua luta contra Voldemort.');
INSERT INTO tb_book (title, author, genre, img_url, book_year, assessment, descri) VALUES ('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'Fábula', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/book7.png', 1943, 5, 'Uma história poética e filosófica sobre um príncipe viajante e suas reflexões sobre a vida.');
INSERT INTO tb_book (title, author, genre, img_url, book_year, assessment, descri) VALUES ('Crime e Castigo', 'Fiódor Dostoiévski', 'Drama', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/book8.png', 1866, 5, 'A luta interna de um jovem estudante após cometer um assassinato.');
INSERT INTO tb_book (title, author, genre, img_url, book_year, assessment, descri) VALUES ('O Hobbit', 'J.R.R. Tolkien', 'Fantasia', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/book9.png', 1937, 5, 'A jornada de Bilbo Bolseiro em busca do tesouro guardado pelo dragão Smaug.');
INSERT INTO tb_book (title, author, genre, img_url, book_year, assessment, descri) VALUES ('A Revolução dos Bichos', 'George Orwell', 'Sátira', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/book10.png', 1945, 5, 'Uma sátira política sobre a Revolução Russa, ambientada em uma fazenda dominada por animais.');
